### ISSUE TITLE
fields out of order

### ISSUE THREAD

**Issue by dataf3l** [Shelnutt2/db2struct#32]
when I run db2struct the original table field order is not respected, is there a way to generate the fields where this original order is respected?

**Comment by sawadyecma** [comment]
@dataf3l 

May be... That problem was solved by this PR(https://github.com/Shelnutt2/db2struct/pull/40) !!!

I have confirmed locally.

**Comment by dataf3l** [comment]
I didn't even remember this project still existed!
thanks for solving the issue :)
